### PR TITLE
Add support for Single Embedded Subdocs

### PR DESCRIPTION
**Pull request by lykmapipo**
Fix TypeError: Cannot read property 'type' of null at Object.keys.reduce (lib/mongoose-hidden.js:124:56)

### CODE REVIEW

**Comment by rwoody** [comment]
Not sure if it works yet, but I suppressed this error by using:

```js
const MySchemaWithSubdoc = Schema({
  aSubdoc: {type: SomeOtherSchema}
})
```

**Comment by mblarsen** [comment]
@rwoody it is not supported at the moment. It does work with nested docs, just not schemas.

**Comment by mblarsen** [comment]
Also, this PR needs to have at minimum the latest tagged version but preferably master merged in. It also needs to be supported by test cases. 

Let me know if you need help with that @lykmapipo

**Comment by mblarsen** [comment]
@lykmapipo I see that you did include tests; the tests dropped because as you'd left `.only` on the new tests. I'll try to merge some of this. Thanks for the contribution :)

**Comment by rwoody** [comment]
@mblarsen Gotcha. Does it work if the Schema also uses this mongoose plugin?

**Comment by mblarsen** [comment]
@rwoody I do not expect that to work, but you can try and let us know. v1.3 has been published to NPM with the Schema support from this PR.

**Comment by lykmapipo** [comment]
@mblarsen My bad with `only` flag on specs(tests). I will be eye open in other contributions.

@rwoody  [The PR I submitted only support single sub schema](https://github.com/mblarsen/mongoose-hidden/pull/31/commits/0d13f78998d6fe5454e09661157317362b321364#diff-910eb6f57886ca16c136101fb1699231R836). I will try to extend to array of sub schema whenever possible and submit another PR.

@mblarsen Cheer.

**Comment by rwoody** [comment]
Thanks for the update. I believe it is actually working for me (need to double check though) with something like:

```js
const mySchema = mongoose.Schema({
  tokens: {type: [TokenSchema], hideJSON: true}
})
```

**Comment by mblarsen** [comment]
@rwoody nested schemas are supported now with 1.9

**Comment by mblarsen** [comment]
@all-contributors add @lykmapipo for bug, maintenance

**Pull request closed without merging**
